-- Convert all primary keys and foreign keys from integer identity to uuid.
-- Safe to run as one transaction; all tables are empty.
BEGIN;
ALTER TABLE public."admin" DROP CONSTRAINT "admin_user_id_fkey";
ALTER TABLE public."admin" DROP CONSTRAINT "admin_book_id_fkey";
ALTER TABLE public."bookcopies" DROP CONSTRAINT "bookcopy_book_id_fkey";
ALTER TABLE public."bookcopies" DROP CONSTRAINT "bookcopy_user_id_fkey";
ALTER TABLE public."fines" DROP CONSTRAINT "fines_loan_id_fkey";
ALTER TABLE public."fines" DROP CONSTRAINT "fines_user_id_fkey";
ALTER TABLE public."loanedbooks" DROP CONSTRAINT "loanedbooks_user_id_fkey";
ALTER TABLE public."loanedbooks" DROP CONSTRAINT "loanedbooks_book_id_fkey";
ALTER TABLE public."reservations" DROP CONSTRAINT "reservation_user_id_fkey";
ALTER TABLE public."reservations" DROP CONSTRAINT "reservation_book_id_fkey";
ALTER TABLE public."admin" ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;
ALTER TABLE public."admin" ALTER COLUMN "Id" TYPE uuid USING gen_random_uuid();
ALTER TABLE public."admin" ALTER COLUMN "Id" SET DEFAULT gen_random_uuid();
ALTER TABLE public."bookcopies" ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;
ALTER TABLE public."bookcopies" ALTER COLUMN "Id" TYPE uuid USING gen_random_uuid();
ALTER TABLE public."bookcopies" ALTER COLUMN "Id" SET DEFAULT gen_random_uuid();
ALTER TABLE public."books" ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;
ALTER TABLE public."books" ALTER COLUMN "Id" TYPE uuid USING gen_random_uuid();
ALTER TABLE public."books" ALTER COLUMN "Id" SET DEFAULT gen_random_uuid();
ALTER TABLE public."fines" ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;
ALTER TABLE public."fines" ALTER COLUMN "Id" TYPE uuid USING gen_random_uuid();
ALTER TABLE public."fines" ALTER COLUMN "Id" SET DEFAULT gen_random_uuid();
ALTER TABLE public."loanedbooks" ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;
ALTER TABLE public."loanedbooks" ALTER COLUMN "Id" TYPE uuid USING gen_random_uuid();
ALTER TABLE public."loanedbooks" ALTER COLUMN "Id" SET DEFAULT gen_random_uuid();
ALTER TABLE public."reservations" ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;
ALTER TABLE public."reservations" ALTER COLUMN "Id" TYPE uuid USING gen_random_uuid();
ALTER TABLE public."reservations" ALTER COLUMN "Id" SET DEFAULT gen_random_uuid();
ALTER TABLE public."users" ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;
ALTER TABLE public."users" ALTER COLUMN "Id" TYPE uuid USING gen_random_uuid();
ALTER TABLE public."users" ALTER COLUMN "Id" SET DEFAULT gen_random_uuid();
ALTER TABLE public."admin" ALTER COLUMN "User_Id" TYPE uuid USING gen_random_uuid();
ALTER TABLE public."admin" ALTER COLUMN "Book_Id" TYPE uuid USING gen_random_uuid();
ALTER TABLE public."bookcopies" ALTER COLUMN "Book_Id" TYPE uuid USING gen_random_uuid();
ALTER TABLE public."bookcopies" ALTER COLUMN "User_Id" TYPE uuid USING gen_random_uuid();
ALTER TABLE public."fines" ALTER COLUMN "Loan_Id" TYPE uuid USING gen_random_uuid();
ALTER TABLE public."fines" ALTER COLUMN "User_Id" TYPE uuid USING gen_random_uuid();
ALTER TABLE public."loanedbooks" ALTER COLUMN "User_id" TYPE uuid USING gen_random_uuid();
ALTER TABLE public."loanedbooks" ALTER COLUMN "Book_id" TYPE uuid USING gen_random_uuid();
ALTER TABLE public."reservations" ALTER COLUMN "User_Id" TYPE uuid USING gen_random_uuid();
ALTER TABLE public."reservations" ALTER COLUMN "Book_Id" TYPE uuid USING gen_random_uuid();
ALTER TABLE public."admin" ADD CONSTRAINT "admin_user_id_fkey" FOREIGN KEY ("User_Id") REFERENCES public."users"("Id");
ALTER TABLE public."admin" ADD CONSTRAINT "admin_book_id_fkey" FOREIGN KEY ("Book_Id") REFERENCES public."books"("Id");
ALTER TABLE public."bookcopies" ADD CONSTRAINT "bookcopy_book_id_fkey" FOREIGN KEY ("Book_Id") REFERENCES public."books"("Id");
ALTER TABLE public."bookcopies" ADD CONSTRAINT "bookcopy_user_id_fkey" FOREIGN KEY ("User_Id") REFERENCES public."users"("Id");
ALTER TABLE public."fines" ADD CONSTRAINT "fines_loan_id_fkey" FOREIGN KEY ("Loan_Id") REFERENCES public."loanedbooks"("Id");
ALTER TABLE public."fines" ADD CONSTRAINT "fines_user_id_fkey" FOREIGN KEY ("User_Id") REFERENCES public."users"("Id");
ALTER TABLE public."loanedbooks" ADD CONSTRAINT "loanedbooks_user_id_fkey" FOREIGN KEY ("User_id") REFERENCES public."users"("Id");
ALTER TABLE public."loanedbooks" ADD CONSTRAINT "loanedbooks_book_id_fkey" FOREIGN KEY ("Book_id") REFERENCES public."books"("Id");
ALTER TABLE public."reservations" ADD CONSTRAINT "reservation_user_id_fkey" FOREIGN KEY ("User_Id") REFERENCES public."users"("Id");
ALTER TABLE public."reservations" ADD CONSTRAINT "reservation_book_id_fkey" FOREIGN KEY ("Book_Id") REFERENCES public."books"("Id");
COMMIT;
