-- Reverses 001-ids-to-uuid.sql (verified by dry run).
BEGIN;
ALTER TABLE public."admin" DROP CONSTRAINT "admin_user_id_fkey";
ALTER TABLE public."admin" DROP CONSTRAINT "admin_book_id_fkey";
ALTER TABLE public."bookcopies" DROP CONSTRAINT "bookcopy_book_id_fkey";
ALTER TABLE public."bookcopies" DROP CONSTRAINT "bookcopy_user_id_fkey";
ALTER TABLE public."fines" DROP CONSTRAINT "fines_loan_id_fkey";
ALTER TABLE public."fines" DROP CONSTRAINT "fines_user_id_fkey";
ALTER TABLE public."loanedbooks" DROP CONSTRAINT "loanedbooks_user_id_fkey";
ALTER TABLE public."loanedbooks" DROP CONSTRAINT "loanedbooks_book_id_fkey";
ALTER TABLE public."reservations" DROP CONSTRAINT "reservation_user_id_fkey";
ALTER TABLE public."reservations" DROP CONSTRAINT "reservation_book_id_fkey";
ALTER TABLE public."admin" ALTER COLUMN "Id" DROP DEFAULT;
ALTER TABLE public."admin" ALTER COLUMN "Id" TYPE integer USING 0;
ALTER TABLE public."admin" ALTER COLUMN "Id" ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE public."bookcopies" ALTER COLUMN "Id" DROP DEFAULT;
ALTER TABLE public."bookcopies" ALTER COLUMN "Id" TYPE integer USING 0;
ALTER TABLE public."bookcopies" ALTER COLUMN "Id" ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE public."books" ALTER COLUMN "Id" DROP DEFAULT;
ALTER TABLE public."books" ALTER COLUMN "Id" TYPE integer USING 0;
ALTER TABLE public."books" ALTER COLUMN "Id" ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE public."fines" ALTER COLUMN "Id" DROP DEFAULT;
ALTER TABLE public."fines" ALTER COLUMN "Id" TYPE integer USING 0;
ALTER TABLE public."fines" ALTER COLUMN "Id" ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE public."loanedbooks" ALTER COLUMN "Id" DROP DEFAULT;
ALTER TABLE public."loanedbooks" ALTER COLUMN "Id" TYPE integer USING 0;
ALTER TABLE public."loanedbooks" ALTER COLUMN "Id" ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE public."reservations" ALTER COLUMN "Id" DROP DEFAULT;
ALTER TABLE public."reservations" ALTER COLUMN "Id" TYPE integer USING 0;
ALTER TABLE public."reservations" ALTER COLUMN "Id" ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE public."users" ALTER COLUMN "Id" DROP DEFAULT;
ALTER TABLE public."users" ALTER COLUMN "Id" TYPE integer USING 0;
ALTER TABLE public."users" ALTER COLUMN "Id" ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE public."admin" ALTER COLUMN "User_Id" TYPE integer USING 0;
ALTER TABLE public."admin" ALTER COLUMN "Book_Id" TYPE integer USING 0;
ALTER TABLE public."bookcopies" ALTER COLUMN "Book_Id" TYPE integer USING 0;
ALTER TABLE public."bookcopies" ALTER COLUMN "User_Id" TYPE integer USING 0;
ALTER TABLE public."fines" ALTER COLUMN "Loan_Id" TYPE integer USING 0;
ALTER TABLE public."fines" ALTER COLUMN "User_Id" TYPE integer USING 0;
ALTER TABLE public."loanedbooks" ALTER COLUMN "User_id" TYPE integer USING 0;
ALTER TABLE public."loanedbooks" ALTER COLUMN "Book_id" TYPE integer USING 0;
ALTER TABLE public."reservations" ALTER COLUMN "User_Id" TYPE integer USING 0;
ALTER TABLE public."reservations" ALTER COLUMN "Book_Id" TYPE integer USING 0;
ALTER TABLE public."admin" ADD CONSTRAINT "admin_user_id_fkey" FOREIGN KEY ("User_Id") REFERENCES public."users"("Id");
ALTER TABLE public."admin" ADD CONSTRAINT "admin_book_id_fkey" FOREIGN KEY ("Book_Id") REFERENCES public."books"("Id");
ALTER TABLE public."bookcopies" ADD CONSTRAINT "bookcopy_book_id_fkey" FOREIGN KEY ("Book_Id") REFERENCES public."books"("Id");
ALTER TABLE public."bookcopies" ADD CONSTRAINT "bookcopy_user_id_fkey" FOREIGN KEY ("User_Id") REFERENCES public."users"("Id");
ALTER TABLE public."fines" ADD CONSTRAINT "fines_loan_id_fkey" FOREIGN KEY ("Loan_Id") REFERENCES public."loanedbooks"("Id");
ALTER TABLE public."fines" ADD CONSTRAINT "fines_user_id_fkey" FOREIGN KEY ("User_Id") REFERENCES public."users"("Id");
ALTER TABLE public."loanedbooks" ADD CONSTRAINT "loanedbooks_user_id_fkey" FOREIGN KEY ("User_id") REFERENCES public."users"("Id");
ALTER TABLE public."loanedbooks" ADD CONSTRAINT "loanedbooks_book_id_fkey" FOREIGN KEY ("Book_id") REFERENCES public."books"("Id");
ALTER TABLE public."reservations" ADD CONSTRAINT "reservation_user_id_fkey" FOREIGN KEY ("User_Id") REFERENCES public."users"("Id");
ALTER TABLE public."reservations" ADD CONSTRAINT "reservation_book_id_fkey" FOREIGN KEY ("Book_Id") REFERENCES public."books"("Id");
COMMIT;
