// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'09b360fb787c4dbb97f73f701a5cec5ad44f3a93087431533f013fcb3de7fa12'>;
export type ExecutionHash =
  ExecutionHashBase<'c086a7597d693fbc34742f8b5d61bd545c802d64b8816a803f1c2a3f8e615d28'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Admin: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
      readonly bookId: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly Book: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly genre: CodecTypes['pg/text@1']['output'];
      readonly author: CodecTypes['pg/text@1']['output'];
      readonly isbn: CodecTypes['pg/int4@1']['output'] | null;
      readonly coverImageUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly copiesAvailable: CodecTypes['pg/int4@1']['output'];
    };
    readonly BookCopy: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly bookId: CodecTypes['pg/uuid@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly condition: CodecTypes['pg/text@1']['output'] | null;
      readonly status: CodecTypes['pg/text@1']['output'];
    };
    readonly Fine: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly loanId: CodecTypes['pg/uuid@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
      readonly daysOverDue: CodecTypes['pg/int4@1']['output'];
      readonly amountOwed: CodecTypes['pg/numeric@1']['output'];
      readonly datePaid: CodecTypes['pg/date-string@1']['output'] | null;
    };
    readonly LoanedBook: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly bookId: CodecTypes['pg/uuid@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
      readonly loanDate: CodecTypes['pg/date-string@1']['output'];
      readonly returnDate: CodecTypes['pg/date-string@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
    };
    readonly Reservation: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
      readonly bookId: CodecTypes['pg/uuid@1']['output'];
      readonly reservationDate: CodecTypes['pg/date-string@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly User: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly surname: CodecTypes['pg/text@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly role: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/date-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Admin: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
      readonly bookId: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly Book: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly genre: CodecTypes['pg/text@1']['input'];
      readonly author: CodecTypes['pg/text@1']['input'];
      readonly isbn: CodecTypes['pg/int4@1']['input'] | null;
      readonly coverImageUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly copiesAvailable: CodecTypes['pg/int4@1']['input'];
    };
    readonly BookCopy: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly bookId: CodecTypes['pg/uuid@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly condition: CodecTypes['pg/text@1']['input'] | null;
      readonly status: CodecTypes['pg/text@1']['input'];
    };
    readonly Fine: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly loanId: CodecTypes['pg/uuid@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
      readonly daysOverDue: CodecTypes['pg/int4@1']['input'];
      readonly amountOwed: CodecTypes['pg/numeric@1']['input'];
      readonly datePaid: CodecTypes['pg/date-string@1']['input'] | null;
    };
    readonly LoanedBook: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly bookId: CodecTypes['pg/uuid@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
      readonly loanDate: CodecTypes['pg/date-string@1']['input'];
      readonly returnDate: CodecTypes['pg/date-string@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
    };
    readonly Reservation: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
      readonly bookId: CodecTypes['pg/uuid@1']['input'];
      readonly reservationDate: CodecTypes['pg/date-string@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly User: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly surname: CodecTypes['pg/text@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly role: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/date-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly admin: {
      readonly Book_Id: CodecTypes['pg/uuid@1']['output'];
      readonly Id: CodecTypes['pg/uuid@1']['output'];
      readonly Name: CodecTypes['pg/text@1']['output'];
      readonly User_Id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly bookcopies: {
      readonly Book_Id: CodecTypes['pg/uuid@1']['output'];
      readonly Condition: CodecTypes['pg/text@1']['output'] | null;
      readonly Id: CodecTypes['pg/uuid@1']['output'];
      readonly Name: CodecTypes['pg/text@1']['output'] | null;
      readonly Status: CodecTypes['pg/text@1']['output'];
      readonly User_Id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly books: {
      readonly Author: CodecTypes['pg/text@1']['output'];
      readonly CopiesAvailable: CodecTypes['pg/int4@1']['output'];
      readonly CoverImageURL: CodecTypes['pg/text@1']['output'] | null;
      readonly Description: CodecTypes['pg/text@1']['output'] | null;
      readonly Genre: CodecTypes['pg/text@1']['output'];
      readonly Id: CodecTypes['pg/uuid@1']['output'];
      readonly ISBN: CodecTypes['pg/int4@1']['output'] | null;
      readonly Title: CodecTypes['pg/text@1']['output'];
    };
    readonly fines: {
      readonly AmountOwed: CodecTypes['pg/numeric@1']['output'];
      readonly DatePaid: CodecTypes['pg/date-string@1']['output'] | null;
      readonly DaysOverDue: CodecTypes['pg/int4@1']['output'];
      readonly Id: CodecTypes['pg/uuid@1']['output'];
      readonly Loan_Id: CodecTypes['pg/uuid@1']['output'];
      readonly User_Id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly loanedbooks: {
      readonly Book_id: CodecTypes['pg/uuid@1']['output'];
      readonly Id: CodecTypes['pg/uuid@1']['output'];
      readonly LoanDate: CodecTypes['pg/date-string@1']['output'];
      readonly ReturnDate: CodecTypes['pg/date-string@1']['output'];
      readonly Status: CodecTypes['pg/text@1']['output'];
      readonly User_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly reservations: {
      readonly Book_Id: CodecTypes['pg/uuid@1']['output'];
      readonly Id: CodecTypes['pg/uuid@1']['output'];
      readonly ReservationDate: CodecTypes['pg/date-string@1']['output'];
      readonly Status: CodecTypes['pg/text@1']['output'] | null;
      readonly User_Id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly users: {
      readonly CreatedAt: CodecTypes['pg/date-string@1']['output'];
      readonly Email: CodecTypes['pg/text@1']['output'];
      readonly Id: CodecTypes['pg/uuid@1']['output'];
      readonly Name: CodecTypes['pg/text@1']['output'];
      readonly Password: CodecTypes['pg/text@1']['output'];
      readonly Role: CodecTypes['pg/text@1']['output'];
      readonly Surname: CodecTypes['pg/text@1']['output'];
      readonly Username: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly admin: {
      readonly Book_Id: CodecTypes['pg/uuid@1']['input'];
      readonly Id: CodecTypes['pg/uuid@1']['input'];
      readonly Name: CodecTypes['pg/text@1']['input'];
      readonly User_Id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly bookcopies: {
      readonly Book_Id: CodecTypes['pg/uuid@1']['input'];
      readonly Condition: CodecTypes['pg/text@1']['input'] | null;
      readonly Id: CodecTypes['pg/uuid@1']['input'];
      readonly Name: CodecTypes['pg/text@1']['input'] | null;
      readonly Status: CodecTypes['pg/text@1']['input'];
      readonly User_Id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly books: {
      readonly Author: CodecTypes['pg/text@1']['input'];
      readonly CopiesAvailable: CodecTypes['pg/int4@1']['input'];
      readonly CoverImageURL: CodecTypes['pg/text@1']['input'] | null;
      readonly Description: CodecTypes['pg/text@1']['input'] | null;
      readonly Genre: CodecTypes['pg/text@1']['input'];
      readonly Id: CodecTypes['pg/uuid@1']['input'];
      readonly ISBN: CodecTypes['pg/int4@1']['input'] | null;
      readonly Title: CodecTypes['pg/text@1']['input'];
    };
    readonly fines: {
      readonly AmountOwed: CodecTypes['pg/numeric@1']['input'];
      readonly DatePaid: CodecTypes['pg/date-string@1']['input'] | null;
      readonly DaysOverDue: CodecTypes['pg/int4@1']['input'];
      readonly Id: CodecTypes['pg/uuid@1']['input'];
      readonly Loan_Id: CodecTypes['pg/uuid@1']['input'];
      readonly User_Id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly loanedbooks: {
      readonly Book_id: CodecTypes['pg/uuid@1']['input'];
      readonly Id: CodecTypes['pg/uuid@1']['input'];
      readonly LoanDate: CodecTypes['pg/date-string@1']['input'];
      readonly ReturnDate: CodecTypes['pg/date-string@1']['input'];
      readonly Status: CodecTypes['pg/text@1']['input'];
      readonly User_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly reservations: {
      readonly Book_Id: CodecTypes['pg/uuid@1']['input'];
      readonly Id: CodecTypes['pg/uuid@1']['input'];
      readonly ReservationDate: CodecTypes['pg/date-string@1']['input'];
      readonly Status: CodecTypes['pg/text@1']['input'] | null;
      readonly User_Id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly users: {
      readonly CreatedAt: CodecTypes['pg/date-string@1']['input'];
      readonly Email: CodecTypes['pg/text@1']['input'];
      readonly Id: CodecTypes['pg/uuid@1']['input'];
      readonly Name: CodecTypes['pg/text@1']['input'];
      readonly Password: CodecTypes['pg/text@1']['input'];
      readonly Role: CodecTypes['pg/text@1']['input'];
      readonly Surname: CodecTypes['pg/text@1']['input'];
      readonly Username: CodecTypes['pg/text@1']['input'];
    };
  };
};

export namespace Models {
  export type public_User = {
    id: CodecTypes['pg/uuid@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    surname: CodecTypes['pg/text@1']['output'];
    username: CodecTypes['pg/text@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    password: CodecTypes['pg/text@1']['output'];
    role: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/date-string@1']['output'];
    admins: public_Admin[];
    bookCopies: public_BookCopy[];
    fines: public_Fine[];
    loanedBooks: public_LoanedBook[];
    reservations: public_Reservation[];
    readonly [RelationKeys]?: 'admins' | 'bookCopies' | 'fines' | 'loanedBooks' | 'reservations';
  };
  export type public_Book = {
    id: CodecTypes['pg/uuid@1']['output'];
    title: CodecTypes['pg/text@1']['output'];
    description: CodecTypes['pg/text@1']['output'] | null;
    genre: CodecTypes['pg/text@1']['output'];
    author: CodecTypes['pg/text@1']['output'];
    isbn: CodecTypes['pg/int4@1']['output'] | null;
    coverImageUrl: CodecTypes['pg/text@1']['output'] | null;
    copiesAvailable: CodecTypes['pg/int4@1']['output'];
    admins: public_Admin[];
    bookCopies: public_BookCopy[];
    loanedBooks: public_LoanedBook[];
    reservations: public_Reservation[];
    readonly [RelationKeys]?: 'admins' | 'bookCopies' | 'loanedBooks' | 'reservations';
  };
  export type public_Admin = {
    id: CodecTypes['pg/uuid@1']['output'];
    userId: CodecTypes['pg/uuid@1']['output'];
    bookId: CodecTypes['pg/uuid@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    book: public_Book;
    user: public_User;
    readonly [RelationKeys]?: 'book' | 'user';
  };
  export type public_BookCopy = {
    id: CodecTypes['pg/uuid@1']['output'];
    bookId: CodecTypes['pg/uuid@1']['output'];
    userId: CodecTypes['pg/uuid@1']['output'];
    name: CodecTypes['pg/text@1']['output'] | null;
    condition: CodecTypes['pg/text@1']['output'] | null;
    status: CodecTypes['pg/text@1']['output'];
    book: public_Book;
    user: public_User;
    readonly [RelationKeys]?: 'book' | 'user';
  };
  export type public_LoanedBook = {
    id: CodecTypes['pg/uuid@1']['output'];
    bookId: CodecTypes['pg/uuid@1']['output'];
    userId: CodecTypes['pg/uuid@1']['output'];
    loanDate: CodecTypes['pg/date-string@1']['output'];
    returnDate: CodecTypes['pg/date-string@1']['output'];
    status: CodecTypes['pg/text@1']['output'];
    book: public_Book;
    fines: public_Fine[];
    user: public_User;
    readonly [RelationKeys]?: 'book' | 'fines' | 'user';
  };
  export type public_Fine = {
    id: CodecTypes['pg/uuid@1']['output'];
    loanId: CodecTypes['pg/uuid@1']['output'];
    userId: CodecTypes['pg/uuid@1']['output'];
    daysOverDue: CodecTypes['pg/int4@1']['output'];
    amountOwed: CodecTypes['pg/numeric@1']['output'];
    datePaid: CodecTypes['pg/date-string@1']['output'] | null;
    loan: public_LoanedBook;
    user: public_User;
    readonly [RelationKeys]?: 'loan' | 'user';
  };
  export type public_Reservation = {
    id: CodecTypes['pg/uuid@1']['output'];
    userId: CodecTypes['pg/uuid@1']['output'];
    bookId: CodecTypes['pg/uuid@1']['output'];
    reservationDate: CodecTypes['pg/date-string@1']['output'];
    status: CodecTypes['pg/text@1']['output'] | null;
    book: public_Book;
    user: public_User;
    readonly [RelationKeys]?: 'book' | 'user';
  };
}

export declare const models: {
  public: {
    User: Models.public_User;
    Book: Models.public_Book;
    Admin: Models.public_Admin;
    BookCopy: Models.public_BookCopy;
    LoanedBook: Models.public_LoanedBook;
    Fine: Models.public_Fine;
    Reservation: Models.public_Reservation;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly admin: {
              columns: {
                readonly Id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly User_Id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly Book_Id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly Name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['Id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'admin_User_Id_idx_99d17088';
                  readonly prefix: 'admin_User_Id_idx';
                  readonly columns: readonly ['User_Id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'admin_Book_Id_idx_f7bddef2';
                  readonly prefix: 'admin_Book_Id_idx';
                  readonly columns: readonly ['Book_Id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'admin';
                    readonly columns: readonly ['User_Id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['Id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'admin';
                    readonly columns: readonly ['Book_Id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'books';
                    readonly columns: readonly ['Id'];
                  };
                },
              ];
            };
            readonly bookcopies: {
              columns: {
                readonly Id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly Book_Id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly User_Id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly Name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly Condition: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly Status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['Id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'bookcopies_Book_Id_idx_f7bddef2';
                  readonly prefix: 'bookcopies_Book_Id_idx';
                  readonly columns: readonly ['Book_Id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'bookcopies_User_Id_idx_99d17088';
                  readonly prefix: 'bookcopies_User_Id_idx';
                  readonly columns: readonly ['User_Id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'bookcopies';
                    readonly columns: readonly ['Book_Id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'books';
                    readonly columns: readonly ['Id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'bookcopies';
                    readonly columns: readonly ['User_Id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['Id'];
                  };
                },
              ];
            };
            readonly books: {
              columns: {
                readonly Id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly Title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly Genre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Author: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly ISBN: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly CoverImageURL: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly CopiesAvailable: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['Id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly fines: {
              columns: {
                readonly Id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly Loan_Id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly User_Id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly DaysOverDue: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly AmountOwed: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly DatePaid: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['Id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'fines_Loan_Id_idx_27a456d6';
                  readonly prefix: 'fines_Loan_Id_idx';
                  readonly columns: readonly ['Loan_Id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'fines_User_Id_idx_99d17088';
                  readonly prefix: 'fines_User_Id_idx';
                  readonly columns: readonly ['User_Id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'fines';
                    readonly columns: readonly ['Loan_Id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'loanedbooks';
                    readonly columns: readonly ['Id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'fines';
                    readonly columns: readonly ['User_Id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['Id'];
                  };
                },
              ];
            };
            readonly loanedbooks: {
              columns: {
                readonly Id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly Book_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly User_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly LoanDate: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
                readonly ReturnDate: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
                readonly Status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['Id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'loanedbooks_Book_id_idx_df807605';
                  readonly prefix: 'loanedbooks_Book_id_idx';
                  readonly columns: readonly ['Book_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'loanedbooks_User_id_idx_7e9a62fd';
                  readonly prefix: 'loanedbooks_User_id_idx';
                  readonly columns: readonly ['User_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'loanedbooks';
                    readonly columns: readonly ['Book_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'books';
                    readonly columns: readonly ['Id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'loanedbooks';
                    readonly columns: readonly ['User_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['Id'];
                  };
                },
              ];
            };
            readonly reservations: {
              columns: {
                readonly Id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly User_Id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly Book_Id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly ReservationDate: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
                readonly Status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['Id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'reservations_User_Id_idx_99d17088';
                  readonly prefix: 'reservations_User_Id_idx';
                  readonly columns: readonly ['User_Id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'reservations_Book_Id_idx_f7bddef2';
                  readonly prefix: 'reservations_Book_Id_idx';
                  readonly columns: readonly ['Book_Id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'reservations';
                    readonly columns: readonly ['User_Id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['Id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'reservations';
                    readonly columns: readonly ['Book_Id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'books';
                    readonly columns: readonly ['Id'];
                  };
                },
              ];
            };
            readonly users: {
              columns: {
                readonly Id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly Name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Surname: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Username: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly CreatedAt: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['Id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly users: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly books: { readonly namespace: 'public' & NamespaceId; readonly model: 'Book' };
    readonly admin: { readonly namespace: 'public' & NamespaceId; readonly model: 'Admin' };
    readonly bookcopies: { readonly namespace: 'public' & NamespaceId; readonly model: 'BookCopy' };
    readonly loanedbooks: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'LoanedBook';
    };
    readonly fines: { readonly namespace: 'public' & NamespaceId; readonly model: 'Fine' };
    readonly reservations: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Reservation';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Admin: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly bookId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly book: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Book' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['bookId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'admin';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'Id' };
                readonly userId: { readonly column: 'User_Id' };
                readonly bookId: { readonly column: 'Book_Id' };
                readonly name: { readonly column: 'Name' };
              };
            };
          };
          readonly Book: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly genre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly author: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isbn: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly coverImageUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly copiesAvailable: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly admins: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Admin';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['bookId'];
                };
              };
              readonly bookCopies: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'BookCopy';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['bookId'];
                };
              };
              readonly loanedBooks: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'LoanedBook';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['bookId'];
                };
              };
              readonly reservations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Reservation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['bookId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'books';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'Id' };
                readonly title: { readonly column: 'Title' };
                readonly description: { readonly column: 'Description' };
                readonly genre: { readonly column: 'Genre' };
                readonly author: { readonly column: 'Author' };
                readonly isbn: { readonly column: 'ISBN' };
                readonly coverImageUrl: { readonly column: 'CoverImageURL' };
                readonly copiesAvailable: { readonly column: 'CopiesAvailable' };
              };
            };
          };
          readonly BookCopy: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly bookId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly condition: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly book: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Book' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['bookId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'bookcopies';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'Id' };
                readonly bookId: { readonly column: 'Book_Id' };
                readonly userId: { readonly column: 'User_Id' };
                readonly name: { readonly column: 'Name' };
                readonly condition: { readonly column: 'Condition' };
                readonly status: { readonly column: 'Status' };
              };
            };
          };
          readonly Fine: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly loanId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly daysOverDue: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly amountOwed: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly datePaid: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
            };
            readonly relations: {
              readonly loan: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'LoanedBook';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['loanId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'fines';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'Id' };
                readonly loanId: { readonly column: 'Loan_Id' };
                readonly userId: { readonly column: 'User_Id' };
                readonly daysOverDue: { readonly column: 'DaysOverDue' };
                readonly amountOwed: { readonly column: 'AmountOwed' };
                readonly datePaid: { readonly column: 'DatePaid' };
              };
            };
          };
          readonly LoanedBook: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly bookId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly loanDate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly returnDate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly book: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Book' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['bookId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly fines: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Fine' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['loanId'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'loanedbooks';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'Id' };
                readonly bookId: { readonly column: 'Book_id' };
                readonly userId: { readonly column: 'User_id' };
                readonly loanDate: { readonly column: 'LoanDate' };
                readonly returnDate: { readonly column: 'ReturnDate' };
                readonly status: { readonly column: 'Status' };
              };
            };
          };
          readonly Reservation: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly bookId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly reservationDate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly status: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly book: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Book' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['bookId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'reservations';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'Id' };
                readonly userId: { readonly column: 'User_Id' };
                readonly bookId: { readonly column: 'Book_Id' };
                readonly reservationDate: { readonly column: 'ReservationDate' };
                readonly status: { readonly column: 'Status' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly surname: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly username: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
            };
            readonly relations: {
              readonly admins: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Admin';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly bookCopies: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'BookCopy';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly fines: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Fine' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly loanedBooks: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'LoanedBook';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly reservations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Reservation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'users';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'Id' };
                readonly name: { readonly column: 'Name' };
                readonly surname: { readonly column: 'Surname' };
                readonly username: { readonly column: 'Username' };
                readonly email: { readonly column: 'Email' };
                readonly password: { readonly column: 'Password' };
                readonly role: { readonly column: 'Role' };
                readonly createdAt: { readonly column: 'CreatedAt' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'admin';
            readonly column: 'Id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'bookcopies';
            readonly column: 'Id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'books';
            readonly column: 'Id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'fines';
            readonly column: 'Id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'loanedbooks';
            readonly column: 'Id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'reservations';
            readonly column: 'Id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'users';
            readonly column: 'Id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
